query listRepositories ($number_of_repos: Int! = 1) {
  viewer {
    name
    repositories(last: $number_of_repos) {
      nodes {
        name
      }
    }
  }
}


query repositoryLabels ($owner: String!, $name: String!) {
  repository(owner: $owner, name: $name) {
    repositoryId: id
    repositoryName: name

    issues(last:20, states:CLOSED) {
      totalCount
      pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage        
      }
      edges {
        cursor
        node {
          issueTitle: title
          issueUrl: url
          issueLabels: labels(first:5) {
            edges {
              node {
                name
              }
            }
          }
        }
      }
    }

    moreIssues: issues(last:20, states:CLOSED) {
      totalCount
      pageInfo {
        startCursor
        endCursor
        hasNextPage
        hasPreviousPage        
      }
      edges {
        cursor
        node {
          issueLabels: labels(first:5) {
            edges {
              node {
                name
              }
            }
          }
        }
      }
    }
    
    
  }
}


query findIssue ($issueId: Int!) {
  repository(owner:"octocat", name:"Hello-World") {
    issue(number:$issue) {
      id
    }
  }
}

mutation AddReactionToIssue {
  addReaction(input:{subjectId:"MDU6SXNzdWUyMzEzOTE1NTE=",content:HOORAY}) {
    reaction {
      content
    }
    subject {
      id
    }
  }
}



mutation Mutation10 ($myVar:AddReactionInput!) {
  addReaction(input:$myVar) {
    reaction {
      content
    }
    subject {
      id
    }
  }
}


query Test2 {
  node(id:"MDQ6VXNlcjU4MzIzMQ==") {
   ... on User {
      name
      login
    }
  }
}

query Test3 {
  node(id:"MDQ6VXNlcjU4MzIzMQ==") {
     __typename
  }
}


query Test4 {
  __type(name: "Repository") {
    name
    kind
    description
    fields {
      name
    }
  }
}

query Test5 {
  __schema {
    types {
      name
      kind
      description
      fields {
        name
      }
    }
  }
}


query Test6 {
  viewer {
    repositories(first: 50) {
      edges {
        repository:node {
          name

          issues(first: 10) {
            totalCount
            edges {
              node {
                title
                bodyHTML
              }
            }
          }
        }
      }
    }
  }
}



query Test7 ($count: Int! = 10) {
  viewer {
    repositories(first: 50) {
      edges {
        repository:node {
          name

          pullRequests(first: 20) {
            edges {
              pullRequest:node {
                title

                comments(first: $count) {
                  edges {
                    comment:node {
                      bodyHTML
                    }
                  }
                }
              }
            }
          }

          issues(first: 20) {
            totalCount
            edges {
              issue:node {
                title
                bodyHTML

                comments(first: $count) {
                  edges {
                    comment:node {
                      bodyHTML
                    }
                  }
                }
              }
            }
          }
        }
      }
    }

    followers(first: $count) {
      edges {
        follower:node {
          login
        }
      }
    }
  }
}




query Test8 {
  viewer {
    login
    repositories(first: 100) {
      edges {
        node {
          id

          issues(first: 50) {
            edges {
              node {
                id

                labels(first: 60) {
                  edges {
                    node {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
